BEGIN
  DBMS_CLOUD.drop_credential(credential_name => 'OBJ_STORE_CRED');
END;
/

DROP TABLE ANALYZED_COMMENTS;

DROP TABLE AVG_GAS_PRICES_BY_GALLON_NYC;

DROP TABLE EV_REBATE_COMMENTS;

DROP TABLE GLOBAL_OIL_PRICES;

DROP TABLE NORWAY_CAR_SALES;

DROP TABLE TESLA_STOCK_PRICES;

DROP TABLE US_CAR_SALES_2011;

