DROP TABLE education;

CREATE TABLE "EDUCATION" 
   (	"TABLENAME" VARCHAR2(26 BYTE), 
	"STATECODE" NUMBER(38,0), 
	"DISTRICTCODE" NUMBER(38,0), 
	"TOWNCODE" NUMBER(38,0), 
	"TOTALRURALURBAN" VARCHAR2(26 BYTE), 
	"AREANAME" VARCHAR2(26 BYTE), 
	"AGEGROUP" VARCHAR2(26 BYTE), 
	"TOTALPERSONS" NUMBER(38,0), 
	"TOTALMALES" NUMBER(38,0), 
	"TOTALFEMALES" NUMBER(38,0), 
	"ILLITERATEPERSONS" NUMBER(38,0), 
	"ILLITERATEMALES" NUMBER(38,0), 
	"ILLITERATEFEMALES" NUMBER(38,0), 
	"LITERATEPERSONS" NUMBER(38,0), 
	"LITERATEMALES" NUMBER(38,0), 
	"LITERATEFEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELLITERATEWITHOUTEDUCATIONALLEVELPERSONS" NUMBER(38,0), 
	"EDUCATIONALLEVELLITERATEWITHOUTEDUCATIONALLEVELMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELLITERATEWITHOUTEDUCATIONALLEVELFEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELBELOWPRIMARYPERSONS" NUMBER(38,0), 
	"EDUCATIONALLEVELBELOWPRIMARYMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELBELOWPRIMARYFEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELPRIMARYPERSONS" NUMBER(38,0), 
	"EDUCATIONALLEVELPRIMARYMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELPRIMARYFEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELMIDDLEPERSONS" NUMBER(38,0), 
	"EDUCATIONALLEVELMIDDLEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELMIDDLEFEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELMATRICSECONDARYPERSONS" NUMBER(38,0), 
	"EDUCATIONALLEVELMATRICSECONDARYMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELMATRICSECONDARYFEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELHIGHERSECONDARYINTERMEDIATEPREUNIVERSITYSENIORSECONDARYPERSONS" NUMBER(38,0), 
	"EDUCATIONALLEVELHIGHERSECONDARYINTERMEDIATEPREUNIVERSITYSENIORSECONDARYMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELHIGHERSECONDARYINTERMEDIATEPREUNIVERSITYSENIORSECONDARYFEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELNONTECHNICALDIPLOMAORCERTIFICATENOTEQUALTODEGREEPERSONS" NUMBER(38,0), 
	"EDUCATIONALLEVELNONTECHNICALDIPLOMAORCERTIFICATENOTEQUALTODEGREEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELNONTECHNICALDIPLOMAORCERTIFICATENOTEQUALTODEGREEFEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELTECHNICALDIPLOMAORCERTIFICATENOTEQUALTODEGREEPERSONS" NUMBER(38,0), 
	"EDUCATIONALLEVELTECHNICALDIPLOMAORCERTIFICATENOTEQUALTODEGREEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELTECHNICALDIPLOMAORCERTIFICATENOTEQUALTODEGREEFEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELGRADUATEABOVEPERSONS" NUMBER(38,0), 
	"EDUCATIONALLEVELGRADUATEABOVEMALES" NUMBER(38,0), 
	"EDUCATIONALLEVELGRADUATEABOVEFEMALES" NUMBER(38,0), 
	"UNCLASSIFIEDPERSONS" NUMBER(38,0), 
	"UNCLASSIFIEDMALES" NUMBER(38,0), 
	"UNCLASSIFIEDFEMALES" NUMBER(38,0)
   );
   
-----------------------------------------------------------------------------------------------

--If you have your own OCI Object Store username and password, replace them here.
set define off
begin
  DBMS_CLOUD.create_credential(
    credential_name => 'OBJ_STORE_CRED',
    username => 'api.user',
    password => 'W<a:Yh#rlIDmT4{ltyoU'
  );
end;
/
set define on


-----------------------------------------------------------------------------------------------

/* Specify the real base_URL for your OCI Object Storage in the define base_URL line below*/
/* change dwcsdemo to your real tenancy name. The name is case-sensitive. */
/* change DEMO_DATA to your real bucket name. The name is case-sensitive. */
/* change us-ashburn-1 to your real region name. The name is case-sensitive. */
/* you can find these values on the OCI Console .. Storage .. Object Storage screen */
set define on
define base_URL='https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/gse00015649/Asset'


begin
 dbms_cloud.copy_data(
    table_name =>'EDUCATION',
    credential_name =>'OBJ_STORE_CRED',
    file_uri_list =>'&base_URL/TownwiseeducationKarnataka.csv',
    format => json_object('ignoremissingcolumns' value 'true', 'removequotes' value 'true')
 );
end;
/

-----------------------------------------------------------------------------------------------

select count(*) from education;

commit;
-----------------------------------------------------------------------------------------------
