
DROP TABLE OLIST_CUSTOMERS_DATASET;

DROP TABLE OLIST_GEOLOCATION_DATASET;

DROP TABLE OLIST_ORDER_ITEMS_DATASET;

DROP TABLE OLIST_ORDER_PAYMENTS_DATASET;

DROP TABLE OLIST_ORDER_REVIEWS_DATASET;

DROP TABLE OLIST_ORDERS_DATASET;

DROP TABLE OLIST_PRODUCTS_DATASET;

DROP TABLE OLIST_SELLERS_DATASET;

DROP TABLE PRODUCT_CATEGORY_NAME_TRANSLATION;
